export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILIURE = "LOGIN_USER_FAILIURE";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILIURE = "REGISTER_USER_FAILIURE";

export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILIURE = "GET_USER_PROFILE_FAILIURE";

export const LOGOUT = "LOGOUT";

export const OTP_VERIFICATION_FAILIURE = "OTP_VERIFICATION_FAILIURE";
export const OTP_VERIFICATION_SUCCESS = "OTP_VERIFICATION_SUCCESS";

export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAILIURE = "UPDATE_USER_PROFILE_FAILIURE";

export const FIND_USER_BY_ID_REQUEST = "FIND_USER_BY_ID_REQUEST";
export const FIND_USER_BY_ID_SUCCESS = "FIND_USER_BY_ID_SUCCESS";
export const FIND_USER_BY_ID_FAILIURE = "FIND_USER_BY_ID_FAILIURE";

export const FOLLOW_USER_REQUEST = "FOLLOW_USER_REQUEST";
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";
export const FOLLOW_USER_FAILIURE = "FOLLOW_USER_FAILIURE";
