export const TWEET_CREATE_REQUEST = "TWEET_CREATE_REQUEST";
export const TWEET_CREATE_SUCCESS = "TWEET_CREATE_SUCCESS";
export const TWEET_CREATE_FAILIURE = "TWEET_CREATE_FAILIURE";

export const TWEET_DELETE_REQUEST = "TWEET_DELETE_REQUEST";
export const TWEET_DELETE_SUCCESS = "TWEET_DELETE_SUCCESS";
export const TWEET_DELETE_FAILIURE = "TWEET_DELETE_FAILIURE";

export const GET_ALL_TWEETS_REQUEST = "GET_ALL_TWEETS_REQUEST";
export const GET_ALL_TWEETS_SUCCESS = "GET_ALL_TWEETS_SUCCESS";
export const GET_ALL_TWEETS_FAILIURE = "GET_ALL_TWEETS_FAILIURE";

export const GET_USER_TWEETS_REQUEST = "GET_USER_TWEETS_REQUEST";
export const GET_USER_TWEETS_SUCCESS = "GET_USER_TWEETS_SUCCESS";
export const GET_USER_TWEETS_FAILIURE = "GET_USER_TWEETS_FAILIURE";

export const TWEETS_LIKED_BY_USER_BY_ID_REQUEST =
  "TWEETS_LIKED_BY_USER_BY_ID_REQUEST";
export const TWEETS_LIKED_BY_USER_BY_ID_SUCCESS =
  "TWEETS_LIKED_BY_USER_BY_ID_SUCCESS";
export const TWEETS_LIKED_BY_USER_BY_ID_FAILIURE =
  "TWEETS_LIKED_BY_USER_BY_ID_FAILIURE";

export const GET_TWEET_LIKED_BY_USER_REQUEST =
  "GET_TWEET_LIKED_BY_USER_REQUEST";
export const GET_TWEET_LIKED_BY_USER_SUCCESS =
  "GET_TWEET_LIKED_BY_USER_SUCCESS";
export const GET_TWEET_LIKED_BY_USER_FAILIURE =
  "GET_TWEET_LIKED_BY_USER_FAILIURE";

export const FIND_TWEETS_BY_ID_REQUEST = "FIND_TWEETS_BY_ID_REQUEST";
export const FIND_TWEETS_BY_ID_SUCCESS = "FIND_TWEETS_BY_ID_SUCCESS";
export const FIND_TWEETS_BY_ID_FAILIURE = "FIND_TWEETS_BY_ID_FAILIURE";

export const REPLY_TO_TWEET_REQUEST = "REPLY_TO_TWEET_REQUEST";
export const REPLY_TO_TWEET_SUCCESS = "REPLY_TO_TWEET_SUCCESS";
export const REPLY_TO_TWEET_FAILIURE = "REPLY_TO_TWEET_FAILIURE";

export const RETWEET_REQUEST = "RETWEET_REQUEST";
export const RETWEET_SUCCESS = "RETWEET_SUCCESS";
export const RETWEET_FAILIURE = "RETWEET_FAILIURE";

export const LIKE_TWEETS_REQUEST = "LIKE_TWEETS_REQUEST";
export const LIKE_TWEETS_SUCCESS = "LIKE_TWEETS_SUCCESS";
export const LIKE_TWEETS_FAILIURE = "LIKE_TWEETS_FAILIURE";

export const GET_ALL_REPLIES_BY_USER_REQUEST =
  "GET_ALL_REPLIES_BY_USER_REQUEST";
export const GET_ALL_REPLIES_BY_USER_SUCCESS =
  "GET_ALL_REPLIES_BY_USER_SUCCESS";
export const GET_ALL_REPLIES_BY_USER_FAILIURE =
  "GET_ALL_REPLIES_BY_USER_FAILIURE";

export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILIURE = "SEARCH_FAILIURE";
